#!/usr/bin/env bash

# get_fattura_pa
#
# Copyright (c) 2018 Enio Carboni - Italy    (see https://github.com/eniocarboni/p7m)
#               2019 Franco Masotti (frnmst) <franco.masotti@live.com>
#
# This file is part of get-fattura-pa.
#
# get-fattura-pa is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# get-fattura-pa is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with get-fattura-pa.  If not, see <https://www.gnu.org/licenses/>.

. ./get_fattura_pa.conf

check_dependencies()
{
    command -V \
        xmlstarlet \
        gawk \
        sha256sum \
        curl \
        openssl \
        base64
}

check_files()
{
    local metadata_file="${1}"; assert_isinstance "${metadata_file}" str
    local signed_file="${2}"; assert_isinstance "${signed_file}" str
    local ignore_checksum_check="${3}"; assert_isinstance \
        "${ignore_checksum_check}" bool

    { [ -f "${signed_file}" ] \
        && openssl pkcs7 -print_certs -text -noout -inform DER \
        -in "${signed_file}"; } || return 1
    [ "${ignore_checksum_check}" = 'true' ] && return 0
    { [ -f "${metadata_file}" ] && xmlstarlet val "${metadata_file}"; } \
        || return 1
}

check_hash()
{
    local metadata_file="${1}"; assert_isinstance "${metadata_file}" str
    local signed_file="${2}"; assert_isinstance "${signed_file}" str
    local ignore_checksum_check="${3}"; assert_isinstance \
        "${ignore_checksum_check}" bool
    local metadata_file_xml_namespace="${4}"; assert_isinstance \
        "${metadata_file_xml_namespace}" str
    # Assume metadata_file is a valid XML file.

    [ "${ignore_checksum_check}" = 'true' ] && return 0

    # TODO: assert original file name == name reported on the metadata file.

    local original_hash="$(xmlstarlet sel \
        -N x="${metadata_file_xml_namespace}" \
        --template --match '//x:FileMetadati/Hash' \
        --value-of . "${metadata_file}")"
    local computed_hash="$(sha256sum --binary "${signed_file}" \
        | gawk '{print $1}')"

    [ "${original_hash}" = "${computed_hash}" ] || return 1
}

get_certificates()
{
    local trusted_certificates_list_url="${1}"; assert_isinstance \
        "${trusted_certificates_list_url}" str
    local trusted_certificates_list_encoded_file="${2}"; assert_isinstance \
        "${trusted_certificates_list_encoded_file}" str
    local trusted_certificates_list_decoded_file="${3}"; assert_isinstance \
        "${trusted_certificates_list_decoded_file}" str
    local force_trusted_certificates_list_download="${4}"; assert_isinstance \
        "${force_trusted_certificates_list_download}" bool
    local trusted_certificates_list_encoded_file_xml_namespace="${5}"; assert_isinstance \
        "${trusted_certificates_list_encoded_file_xml_namespace}" str

    if [ "${force_trusted_certificates_list_download}" = 'true' ] \
        || { [ ! -f "${trusted_certificates_list_encoded_file}" ] \
             && [ ! -f "${trusted_certificates_list_decoded_file}" ]; }; then
        curl --progress-bar --retry 2 \
            --output "${trusted_certificates_list_encoded_file}" \
            "${trusted_certificates_list_url}"

        xmlstarlet val "${trusted_certificates_list_encoded_file}" || return 1

        xmlstarlet sel -N x="${trusted_certificates_list_encoded_file_xml_namespace}" \
            --template --match "//x:X509Certificate" --value-of . --nl \
            "${trusted_certificates_list_encoded_file}" \
            | while read -r -- cert; do
                printf "%s\n" '-----BEGIN CERTIFICATE-----' >> "${trusted_certificates_list_decoded_file}"
                printf "%s\n" "$(echo "${cert}" | openssl base64 -d -A | openssl base64)" \
                    >> "${trusted_certificates_list_decoded_file}"
                printf "%s\n" '-----END CERTIFICATE-----' >> "${trusted_certificates_list_decoded_file}"
            done
    fi
}

check_signature_and_signers_certificate()
{
    local signed_file="${1}"; assert_isinstance "${signed_file}" str
    local trusted_certificates_list_decoded_file="${2}"; assert_isinstance \
        "${trusted_certificates_list_decoded_file}" str
    local ignore_signature_check="${3}"; assert_isinstance \
        "${ignore_signature_check}" bool
    local ignore_signers_certificate="${4}"; assert_isinstance \
        "${ignore_signers_certificate}" bool

    if [ "${ignore_signature_check}" = 'true' ] \
        && [ "${ignore_signers_certificate}" = 'true' ]; then
        return 0
    elif [ "${ignore_signature_check}" = 'false' ] \
        && [ "${ignore_signers_certificate}" = 'true' ]; then
        openssl smime -verify -noverify \
            -CAfile "${trusted_certificates_list_decoded_file}" \
            -in "${signed_file}" -inform DER -out /dev/null
    elif [ "${ignore_signature_check}" = 'true' ] \
        && [ "${ignore_signers_certificate}" = 'false' ]; then
        openssl smime -nosigs -verify \
            -CAfile "${trusted_certificates_list_decoded_file}" \
            -in "${signed_file}" -inform DER -out /dev/null
    else
        openssl smime -verify \
            -CAfile "${trusted_certificates_list_decoded_file}" \
            -in "${signed_file}" -inform DER -out /dev/null
    fi
}

extract_file()
{
    local signed_file="${1}"; assert_isinstance "${signed_file}" str
    # Assume signed_file ends with .p7m. FIXME (see chain function as well).
    local original_file="${signed_file%%.p7m}"; assert_isinstance \
        "${original_file}" str

    # -verify -noverify means to just extract the file without checking the
    # signer's certificate since this should have already been done in a
    # previous step of the pipeline.
    # Avoid also signature verification (-nosigs) for the same reason.
    openssl smime -nosigs -verify -noverify \
        -in "${signed_file}" -inform DER -out "${original_file}"
}

extract_attachments()
{
    local original_file="${1}"; assert_isinstance "${original_file}" str
    local no_extract_attachments="${2}"; assert_isinstance \
        "${no_extract_attachments}" bool
    local original_file_xml_namespace="${3}"; assert_isinstance \
        "${original_file_xml_namespace}" str

    [ "${no_extract_attachments}" = 'true' ] && return 0

    # We just need to exit if it's not a validated XML file.
    xmlstarlet val "${original_file}" || return 0

    # This is a loop for all the attachments.
    # We will use the nome_attachment as the output file name.
    # We need to remove newline characters between each line of the Attachment
    # field. See:
    # https://stackoverflow.com/questions/14952640/xmlstarlet-removing-linefeed
    xmlstarlet sel --noblanks -N x="${original_file_xml_namespace}" \
        --template --match "//x:FatturaElettronica/FatturaElettronicaBody/Allegati" \
        --value-of "NomeAttachment" -o ' ' \
        --var linebreak --nl --break \
        --value-of "translate(Attachment,\$linebreak,'')" --nl "${original_file}" \
        | while read -r -- nome_attachment attachment; do
            echo "${attachment}" | base64 --decode --ignore-garbage > "${nome_attachment}"
        done
}

pipeline()
{
    local metadata_file="${1}"
    local signed_file="${2}"
    local ignore_checksum_check="${3}"
    local ignore_signers_certificate="${4}"
    local force_trusted_certificates_list_download="${5}"
    local ignore_signature_check="${6}"
    local no_extract_attachments="${7}"

    check_dependencies \
        && check_files "${metadata_file}" "${signed_file}" "${ignore_checksum_check}" \
        && check_hash "${metadata_file}" "${signed_file}" "${ignore_checksum_check}" "${METADATA_FILE_XML_NAMESPACE}" \
        && get_certificates "${TRUSTED_CERTIFICATES_LIST_URL}" "${TRUSTED_CERTIFICATES_LIST_ENCODED_FILE}" "${TRUSTED_CERTIFICATES_LIST_DECODED_FILE}" "${force_trusted_certificates_list_download}" "${TRUSTED_CERTIFICATES_LIST_ENCODED_FILE_XML_NAMESPACE}" \
        && check_signature_and_signers_certificate "${signed_file}" "${TRUSTED_CERTIFICATES_LIST_DECODED_FILE}" "${ignore_signature_check}" "${ignore_signers_certificate}" \
        && extract_file "${signed_file}" \
        && extract_attachments "${signed_file%%.p7m}" "${no_extract_attachments}" "${ORIGINAL_FILE_XML_NAMESPACE}"
}

. ./fbla
. ./fbopt
